#!/bin/bash

DATA="data.json"

function findProperty {
	cat $DATA | jq -c --arg property $1 '.data[$property]'
}

function isSupportedInBrowser {

	local browser=$1
	shift
	local browser_data=$(echo $* | jq -c --arg browser $browser '.stats[$browser]')
	for key in $(echo $browser_data | jq 'keys | .[]')
	do
		unquoted_key=$(echo $key | sed -s "s/^\([\"']\)\(.*\)\1\$/\2/g")
		value=$(echo $browser_data | jq --arg key $unquoted_key '.[$key]')
		if [[ $value == "\"y\"" ]]; then
			echo "true"
			return 0
		fi
	done
	echo "false"
}

function printBrowserSupport {

	if [[ $(isSupportedInBrowser $2 $3) == "true" ]]; then
		echo -en "\033[42m\033[1m" $1 "\033[0m" " "
	else
		echo -en "\033[41m\033[1m" $1 "\033[0m" " "
	fi
}

property=$(findProperty $1)
echo $property | jq '.title'
printBrowserSupport "IE" "ie" "$property"
printBrowserSupport "FF" "firefox" "$property"
printBrowserSupport "Chrome" "chrome" "$property"
printBrowserSupport "IOS" "ios_saf" "$property"
printBrowserSupport "Android" "android" "$property"
echo
